export const COUNTRIES = [
  { name: "Bangladesh", iso3: "bgd" },
  { name: "Burkina Faso", iso3: "bfa" },
  { name: "Burundi", iso3: "bdi" },
  { name: "Central African Republic", iso3: "caf" },
  { name: "Chad", iso3: "tcd" },
  { name: "Colombia", iso3: "col" },
  { name: "Côte d’Ivoire", iso3: "civ" },
  { name: "Democratic Republic of Congo", iso3: "cod" },
  { name: "Egypt", iso3: "egy" },
  { name: "Guinea", iso3: "gin" },
  { name: "Honduras", iso3: "hnd" },
  { name: "Iraq", iso3: "irq" },
  { name: "Kyrgyzstan", iso3: "kgz" },
  { name: "Lebanon", iso3: "lbn" },
  { name: "Mali", iso3: "mli" },
  { name: "Mauritania", iso3: "mrt" },
  { name: "Mozambique", iso3: "moz" },
  { name: "Niger", iso3: "ner" },
  { name: "Nigeria", iso3: "nga" },
  { name: "Pakistan", iso3: "pak" },
  { name: "Philippines", iso3: "phl" },
  { name: "Senegal", iso3: "sen" },
  { name: "Sierra Leone", iso3: "sle" },
  { name: "Somalia", iso3: "som" },
  { name: "South Sudan", iso3: "ssd" },
  { name: "State of Palestine", iso3: "pse" },
  { name: "Sudan", iso3: "sdn" },
  { name: "Syria", iso3: "syr" },
  { name: "Ukraine", iso3: "ukr" },
  { name: "West and Central Africa", iso3: "wca" },
];
